### ISSUE TITLE
UrlUnknown("www.noracooks.com")

### ISSUE THREAD

**Issue by zgcgd** [tmayoff/recipe-rs#56]
Just installed, first attempt to do anything was pulling a recipe from this url: https://www.noracooks.com/wprm_print/quick-easy-red-lentil-dahl. Error in the title is all the message. Can't spend a lot of time on this, report, but hope it helps!

**Comment by tmayoff** [comment]
Thanks for the report. Currently the only supported sites are those that support a particular format (application/jsonld) all others require some manual work, I'll try to figure out an implementation for this.

**Comment by zgcgd** [comment]
No yeah please disregard, just realized the url I was pasting was the one that pops up when you hit "Print", not the actual blog post.

**Comment by tmayoff** [comment]
I don't know if it works for you but it doesn't for me so I'm going to keep this open. Looks like there's an issue with how I'm parsing ld+json schemas

**Comment by tmayoff** [comment]
For my future reference this is the actually recipe URL: https://www.noracooks.com/red-lentil-dahl/.

This should be fixed with the newest version of the [plugin](https://github.com/tmayoff/obsidian-meals/releases/tag/0.3.0)

**Comment by zgcgd** [comment]
Yep, pulling from that URL worked for me. That's what I meant to convey with my last comment. Thanks for looking into this, all the best.
